FROM php:7.4-apache
RUN ls -l /
RUN ls -la

# COPY vendor /var/www/vendor
COPY www /var/www/html
COPY entrypoint-server.sh /entrypoint-server.sh

RUN chmod +x /entrypoint-server.sh
ENTRYPOINT ["/entrypoint-server.sh"]
