name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Run PHP-Apache Docker Action"
      uses: "./.github/actions/php-apache"

    - name: Check if docker ran correctly
      run: |
        docker ps -a
        sleep 5
        docker ps -a
        curl http://localhost:3030

    - name: Check if site runs correctly 2
      run: |
        sleep 30
        docker ps -a
        curl http://localhost:3030
